train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: F:\zyc\AVM_SUPERRES_DATA\Arbitrary
      repeat: 20
      cache: in_memory
  wrapper:
    name: sr-implicit-yuv
    args:
      inp_size: 64
      scale_max: 4
      augment: true
      sample_q: 4096
  batch_size: 64
val_dataset:
  dataset:
    name: image-folder-test
    args:
      root_path: F:\zyc\AVM_SUPERRES_DATA\Arbitrary
      cache: in_memory
  wrapper:
    name: sr-implicit-yuv-test
    args:
      scale_max: 4
  batch_size: 1
data_norm:
  inp:
    sub:
    - 0.5
    div:
    - 0.5
  gt:
    sub:
    - 0.5
    div:
    - 0.5
model:
  name: liif
  args:
    encoder_spec:
      name: NAFNet
      args:
        no_upsampling: true
    imnet_spec:
      name: sinmlp
      args:
        out_dim: 1
        hidden_list:
        - 16
        - 16
optimizer:
  name: adam
  args:
    lr: 0.0001
epoch_max: 1000
multi_step_lr:
  milestones:
  - 200
  - 400
  - 600
  - 800
  gamma: 0.5
epoch_val: 1
epoch_save: 100
